[[snippets]]
  description = "Fix bare git repository after clone"
  command = "git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'; git for-each-ref --format='%(refname:short)' refs/heads | xargs git branch -D; git fetch --prune"
  tag = ["git"]
