[[snippets]]
  description = "Check ssl certificate of domain"
  command = "openssl s_client -showcerts -servername <domain> -connect <domain>:443 2>/dev/null | openssl x509 -inform pem -noout -text | less"
  tag = ["openssl", "ssl", "cert", "certificate"]
